on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: |
      ls -l
      git clone https://github.com/cdbbnnyCode/actions-test
      cd actions-test
      chmod +x deploy.sh
      ./deploy.sh
