on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Run
      run: |
        ls -l
        git clone --depth=1 https://github.com/cdbbnnyCode/actions-test
        cd actions-test
        chmod +x deploy.sh
        ./deploy.sh
      env:
        token: ${{ secrets.GITHUB_TOKEN }}
