on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Run
      run: |
        ls -l
        chmod +x deploy.sh
        ./deploy.sh
      with:
        branch: master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
